//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="IWebServiceArchiving")]
public interface IWebServiceArchiving
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IWebServiceArchiving/DoWork", ReplyAction="http://Microsoft.ServiceModel.Samples/IWebServiceArchiving/DoWorkResponse")]
    void DoWork();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IWebServiceArchiving/DoWork", ReplyAction="http://Microsoft.ServiceModel.Samples/IWebServiceArchiving/DoWorkResponse")]
    System.Threading.Tasks.Task DoWorkAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWebServiceArchivingChannel : IWebServiceArchiving, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WebServiceArchivingClient : System.ServiceModel.ClientBase<IWebServiceArchiving>, IWebServiceArchiving
{
    
    public WebServiceArchivingClient()
    {
    }
    
    public WebServiceArchivingClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WebServiceArchivingClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceArchivingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceArchivingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void DoWork()
    {
        base.Channel.DoWork();
    }
    
    public System.Threading.Tasks.Task DoWorkAsync()
    {
        return base.Channel.DoWorkAsync();
    }
}
